/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KthButton {
        "disabled": boolean;
    }
    interface KthTooltip {
        "message": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLKthButtonElement extends Components.KthButton, HTMLStencilElement {
    }
    var HTMLKthButtonElement: {
        prototype: HTMLKthButtonElement;
        new (): HTMLKthButtonElement;
    };
    interface HTMLKthTooltipElement extends Components.KthTooltip, HTMLStencilElement {
    }
    var HTMLKthTooltipElement: {
        prototype: HTMLKthTooltipElement;
        new (): HTMLKthTooltipElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "kth-button": HTMLKthButtonElement;
        "kth-tooltip": HTMLKthTooltipElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface KthButton {
        "disabled"?: boolean;
    }
    interface KthTooltip {
        "message"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "kth-button": KthButton;
        "kth-tooltip": KthTooltip;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kth-button": LocalJSX.KthButton & JSXBase.HTMLAttributes<HTMLKthButtonElement>;
            "kth-tooltip": LocalJSX.KthTooltip & JSXBase.HTMLAttributes<HTMLKthTooltipElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
